source "https://rubygems.org"

ruby "4.0.2"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "sidekiq"
gem "sidekiq-cron"
gem "bootsnap", require: false
gem "bcrypt", "~> 3.1"
gem "tzinfo-data"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
end
